import type { NegotiationEngineInput } from "../budget-gap/negotiation-input"

export function minimalEngineInput(): NegotiationEngineInput {
  return {
    schemaVersion: "1.0",
    generatedAt: "2026-01-01T00:00:00.000Z",
    studyMeta: { studyId: "T-1", studyName: "Test Study", siteName: "Test Site" },
    decision: "negotiate",
    summary: {
      totalInternalRevenue: 50_000,
      totalSponsorRevenue: 40_000,
      totalGap: -10_000,
      totalGapPerPatient: null,
      projectedStudyGap: null,
      recommendedRevenueTargetAt20Margin: 60_000,
      negativeCashFlowRisk: true,
      primaryAlerts: ["alert"],
    },
    lines: [
      {
        id: "g-m1",
        lineCode: "SF",
        label: "Screen failure fee",
        category: "Screen failure",
        visitName: "Screening",
        quantity: 1,
        unit: "ea",
        internalTotal: 2000,
        sponsorTotalOffer: 0,
        gapAmount: -2000,
        gapPercent: -1,
        status: "missing",
        negotiationPriority: "high",
      },
      {
        id: "g-l1",
        lineCode: "SU",
        label: "Startup",
        category: "Startup",
        visitName: "N/A",
        quantity: 1,
        unit: "ls",
        internalTotal: 10_000,
        sponsorTotalOffer: 6000,
        gapAmount: -4000,
        gapPercent: -0.4,
        status: "loss",
        negotiationPriority: "high",
      },
      {
        id: "g-l2",
        lineCode: "V1",
        label: "Visit A",
        category: "Visit",
        visitName: "V1",
        quantity: 1,
        unit: "v",
        internalTotal: 5000,
        sponsorTotalOffer: 4800,
        gapAmount: -200,
        gapPercent: -0.04,
        status: "loss",
        negotiationPriority: "high",
      },
      {
        id: "g-b1",
        lineCode: "B1",
        label: "Breakeven line",
        category: "Visit",
        visitName: "V2",
        quantity: 1,
        unit: "v",
        internalTotal: 1000,
        sponsorTotalOffer: 1020,
        gapAmount: 20,
        gapPercent: 0.02,
        status: "breakeven",
        negotiationPriority: "medium",
      },
      {
        id: "g-p1",
        lineCode: "P1",
        label: "Profitable line",
        category: "Visit",
        visitName: "V3",
        quantity: 1,
        unit: "v",
        internalTotal: 500,
        sponsorTotalOffer: 700,
        gapAmount: 200,
        gapPercent: 0.4,
        status: "profitable",
        negotiationPriority: "low",
      },
    ],
    missingInvoiceables: [
      {
        id: "m1",
        category: "Screen failure",
        lineCode: "SF",
        label: "Screen failure fee",
        visitName: "Screening",
        quantity: 1,
        unit: "ea",
        internalUnitCost: 2000,
        internalTotal: 2000,
        gapAmount: -2000,
        gapPercent: -1,
        status: "missing",
        notes: "Per-procedure documentation.",
        source: "derived",
      },
    ],
    topNegotiationTargets: [],
    justificationPoints: ["j1"],
    risk: { negativeCashFlowRisk: true, primaryAlerts: ["a"] },
  }
}
