import type {
  BudgetStudyMeta,
  InternalBudgetLine,
  SponsorBudgetLine,
} from "@/lib/cliniq-core/budget-gap"

/**
 * Mock scenario: small Houston/Katy metabolic site — sponsor underpays screening,
 * close-out, startup; omits screen failure fee entirely.
 */
export const houstonKatyDiabetesStudyMeta: BudgetStudyMeta = {
  studyId: "DM-HOU-042",
  studyName: "Phase IIb — GLP-1 adjunct in T2DM (single-site pilot cohort)",
  siteName: "Katy Metabolic Research Center (Houston MSA)",
  patientsInBudget: 12,
  plannedEnrollment: 28,
}

export const houstonKatyInternalBudgetLines: InternalBudgetLine[] = [
  {
    id: "int-1",
    category: "Startup",
    lineCode: "SU-001",
    label: "Site activation & startup",
    visitName: "N/A — study",
    quantity: 1,
    unit: "lump sum",
    internalUnitCost: 48500,
    internalTotal: 48500,
    notes: "Contracts, SIV prep, EMR build, delegation logs, pharmacy setup.",
    source: "internal-model",
  },
  {
    id: "int-2",
    category: "Visit",
    lineCode: "SCR-010",
    label: "Screening visit",
    visitName: "Screening",
    quantity: 18,
    unit: "visit",
    internalUnitCost: 1425,
    internalTotal: 25650,
    notes: "Includes hidden coordinator + PI oversight + lab coordination.",
    source: "internal-model",
  },
  {
    id: "int-3",
    category: "Visit",
    lineCode: "RND-020",
    label: "Randomization / baseline",
    visitName: "Day 1",
    quantity: 12,
    unit: "visit",
    internalUnitCost: 1680,
    internalTotal: 20160,
    notes: "IP accountability, randomization call, pharmacy time.",
    source: "internal-model",
  },
  {
    id: "int-4",
    category: "Visit",
    lineCode: "FU-030",
    label: "On-study follow-up",
    visitName: "Weeks 4–24",
    quantity: 84,
    unit: "visit",
    internalUnitCost: 1180,
    internalTotal: 99120,
    notes: "Avg per visit incl. concierge callbacks & document churn.",
    source: "internal-model",
  },
  {
    id: "int-5",
    category: "Study close-out",
    lineCode: "CO-040",
    label: "Close-out & archiving",
    visitName: "Close-out",
    quantity: 1,
    unit: "lump sum",
    internalUnitCost: 22400,
    internalTotal: 22400,
    notes: "TMF QC, query closure, regulatory binder, IP reconciliation.",
    source: "internal-model",
  },
  {
    id: "int-6",
    category: "Screen failure",
    lineCode: "SF-050",
    label: "Screen failure fee",
    visitName: "Screening",
    quantity: 6,
    unit: "each",
    internalUnitCost: 650,
    internalTotal: 3900,
    notes: "Non-enrolled screens with completed procedures.",
    source: "internal-model",
  },
  {
    id: "int-7",
    category: "Pharmacy / IP handling",
    lineCode: "PH-060",
    label: "Pharmacy handling & IP storage",
    visitName: "Study",
    quantity: 12,
    unit: "patient",
    internalUnitCost: 920,
    internalTotal: 11040,
    notes: "Ambient + monitored storage, accountability visits.",
    source: "internal-model",
  },
  {
    id: "int-8",
    category: "Lab handling & shipping",
    lineCode: "LB-070",
    label: "Specimen processing, dry ice, courier",
    visitName: "Study",
    quantity: 12,
    unit: "patient",
    internalUnitCost: 540,
    internalTotal: 6480,
    notes: "Katy → central lab lane; surge weeks included.",
    source: "internal-model",
  },
]

/**
 * Sponsor CSV-style budget: lower screening, low startup, weak close-out,
 * no screen failure line (omitted).
 */
export const houstonKatySponsorBudgetLines: SponsorBudgetLine[] = [
  {
    id: "sp-1",
    category: "Startup",
    lineCode: "START",
    label: "Site activation & startup",
    visitName: "N/A — study",
    quantity: 1,
    unit: "lump sum",
    sponsorUnitOffer: 32000,
    sponsorTotalOffer: 32000,
    notes: "Sponsor template cap.",
    source: "sponsor-budget",
  },
  {
    id: "sp-2",
    category: "Visit",
    lineCode: "SV1",
    label: "Screening visit",
    visitName: "Screening",
    quantity: 18,
    unit: "visit",
    sponsorUnitOffer: 950,
    sponsorTotalOffer: 17100,
    notes: "Underpays vs Houston staffing reality.",
    source: "sponsor-budget",
  },
  {
    id: "sp-3",
    category: "Visit",
    lineCode: "R1",
    label: "Randomization / baseline",
    visitName: "Day 1",
    quantity: 12,
    unit: "visit",
    sponsorUnitOffer: 1650,
    sponsorTotalOffer: 19800,
    notes: "",
    source: "sponsor-budget",
  },
  {
    id: "sp-4",
    category: "Visit",
    lineCode: "FU",
    label: "On-study follow-up",
    visitName: "Weeks 4–24",
    quantity: 84,
    unit: "visit",
    sponsorUnitOffer: 1225,
    sponsorTotalOffer: 102900,
    notes: "Slightly above internal on this line only.",
    source: "sponsor-budget",
  },
  {
    id: "sp-5",
    category: "Study close-out",
    lineCode: "CO",
    label: "Close-out & archiving",
    visitName: "Close-out",
    quantity: 1,
    unit: "lump sum",
    sponsorUnitOffer: 12000,
    sponsorTotalOffer: 12000,
    notes: "Underestimates TMF + IP reconciliation effort.",
    source: "sponsor-budget",
  },
  {
    id: "sp-6",
    category: "Pharmacy / IP handling",
    lineCode: "RX",
    label: "Pharmacy handling & IP storage",
    visitName: "Study",
    quantity: 12,
    unit: "patient",
    sponsorUnitOffer: 900,
    sponsorTotalOffer: 10800,
    notes: "",
    source: "sponsor-budget",
  },
  {
    id: "sp-7",
    category: "Lab handling & shipping",
    lineCode: "LAB",
    label: "Specimen processing, dry ice, courier",
    visitName: "Study",
    quantity: 12,
    unit: "patient",
    sponsorUnitOffer: 520,
    sponsorTotalOffer: 6240,
    notes: "",
    source: "sponsor-budget",
  },
]
