-- Optional sample rows for Action Center v1 (run after cliniq_action_center_v1.sql).

insert into public.cliniq_action_items (
  id,
  study_id,
  sponsor_id,
  subject_id,
  visit_name,
  line_code,
  action_type,
  owner_role,
  priority,
  status,
  title,
  description,
  expected_amount,
  invoiced_amount,
  missing_amount,
  leakage_status,
  leakage_reason,
  event_log_id,
  billable_instance_id,
  invoice_period_start,
  invoice_period_end
) values
(
  'STUDY-1::SUB-001::Visit 3::ECG::not_invoiced',
  'STUDY-1',
  'SPONSOR-1',
  'SUB-001',
  'Visit 3',
  'ECG',
  'prepare_invoice',
  'billing',
  'low',
  'open',
  'Prepare invoice for ECG on Visit 3',
  'SUB-001 / Visit 3 / ECG has $120 missing because it was not invoiced.',
  120.00,
  0.00,
  120.00,
  'missing',
  'not_invoiced',
  'evt_001',
  'bi_001',
  '2026-04-01',
  '2026-04-30'
),
(
  'STUDY-1::SUB-002::Screening::CBC::missing_documentation',
  'STUDY-1',
  'SPONSOR-1',
  'SUB-002',
  'Screening',
  'CBC',
  'collect_documentation',
  'coordinator',
  'medium',
  'open',
  'Collect documentation for CBC on Screening',
  'SUB-002 / Screening / CBC is blocked pending documentation.',
  220.00,
  0.00,
  220.00,
  'not_invoice_ready',
  'missing_documentation',
  'evt_002',
  'bi_002',
  '2026-04-01',
  '2026-04-30'
),
(
  'STUDY-1::SUB-004::Visit 2::MRI::claim_blocked',
  'STUDY-1',
  'SPONSOR-1',
  'SUB-004',
  'Visit 2',
  'MRI',
  'resolve_claim_issue',
  'finance',
  'high',
  'open',
  'Resolve claim issue for MRI on Visit 2',
  'SUB-004 / Visit 2 / MRI is blocked due to a claim issue.',
  1200.00,
  0.00,
  1200.00,
  'not_invoice_ready',
  'claim_blocked',
  'evt_003',
  'bi_003',
  '2026-04-01',
  '2026-04-30'
);
