/**
 * Remaining 25 starter template fees (full ClinIQ starter = these + 5 core v1 clinical rows in seed).
 * Source of truth for metadata; keep aligned with `supabase/seed/fee_template_engine.sql`.
 */

import type { FeeEngineBehavior } from "./fee-taxonomy"
import type { DefaultRateStrategy } from "./fee-taxonomy"

export type StarterFeeDefinition = {
  fee_code: string
  fee_name: string
  category: string
  unit: string
  trigger_type: string
  trigger_source: string
  billing_cycle: string
  payment_terms: string
  priority: string
  auto_create_billable: boolean
  invoice_required: boolean
  max_days_to_invoice: number | null
  sponsor_visible: boolean
  engine_behavior: FeeEngineBehavior
  default_rate_strategy: DefaultRateStrategy
  justification_template: string
  /** Suggested default_rate when numeric; null when percent-only */
  default_rate: number | null
  range_low: number | null
  range_high: number | null
  percent_rate: number | null
}

/** Five clinical v1 fees (seed/RPC); listed here for combined code lists / tests only. */
export const CORE_V1_CLINICAL_FEE_CODES = [
  "SF-START-001",
  "PP-SCR-001",
  "PP-FUP-001",
  "INV-SF-001",
  "INV-AMD-001",
] as const

export type CoreV1ClinicalFeeCode = (typeof CORE_V1_CLINICAL_FEE_CODES)[number]

/**
 * 25 additional starter rows — normalized shape per build spec.
 */
export const STARTER_FEES_EXTENDED: readonly StarterFeeDefinition[] = [
  {
    fee_code: "SF-IRB-001",
    fee_name: "IRB Initial Submission & Review",
    category: "startup",
    unit: "one_time",
    trigger_type: "regulatory",
    trigger_source: "irb_log",
    billing_cycle: "immediate",
    payment_terms: "net_30",
    priority: "high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 5,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Includes preparation, submission, correspondence, and completion of the initial IRB review process required to activate the study.",
    default_rate: 2500,
    range_low: 1500,
    range_high: 4000,
    percent_rate: null,
  },
  {
    fee_code: "SF-PHARM-001",
    fee_name: "Pharmacy Setup & IP Accountability",
    category: "startup",
    unit: "one_time",
    trigger_type: "setup",
    trigger_source: "pharmacy_log",
    billing_cycle: "immediate",
    payment_terms: "net_30",
    priority: "high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 5,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers investigational product setup, accountability workflow preparation, temperature log readiness, and pharmacy-related study activation tasks.",
    default_rate: 3500,
    range_low: 2000,
    range_high: 5500,
    percent_rate: null,
  },
  {
    fee_code: "SF-SIV-001",
    fee_name: "Site Initiation Visit + Training",
    category: "startup",
    unit: "one_time",
    trigger_type: "training",
    trigger_source: "siv_log",
    billing_cycle: "immediate",
    payment_terms: "net_30",
    priority: "high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 5,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers site initiation visit execution, staff training, and documentation required prior to first patient activity.",
    default_rate: 1800,
    range_low: 1000,
    range_high: 3000,
    percent_rate: null,
  },
  {
    fee_code: "SF-REG-001",
    fee_name: "Regulatory Document Preparation",
    category: "startup",
    unit: "one_time",
    trigger_type: "regulatory",
    trigger_source: "regulatory_log",
    billing_cycle: "immediate",
    payment_terms: "net_30",
    priority: "medium_high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 5,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers compilation, quality review, and submission of regulatory documents required for site activation and sponsor oversight.",
    default_rate: 1200,
    range_low: 600,
    range_high: 2200,
    percent_rate: null,
  },
  {
    fee_code: "PP-RAND-001",
    fee_name: "Randomization / Baseline Visit",
    category: "per_patient_visit",
    unit: "per_visit",
    trigger_type: "visit",
    trigger_source: "visit_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers the randomization and baseline assessment visit performed per protocol after eligibility confirmation.",
    default_rate: 520,
    range_low: 350,
    range_high: 750,
    percent_rate: null,
  },
  {
    fee_code: "PP-EOS-001",
    fee_name: "End of Study / EOS Visit",
    category: "per_patient_visit",
    unit: "per_visit",
    trigger_type: "visit",
    trigger_source: "visit_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium_high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers end-of-study visit activities, final assessments, and documentation required for protocol completion.",
    default_rate: 500,
    range_low: 320,
    range_high: 720,
    percent_rate: null,
  },
  {
    fee_code: "PP-UNS-001",
    fee_name: "Unscheduled / Early Termination Visit",
    category: "per_patient_visit",
    unit: "per_visit",
    trigger_type: "unscheduled_visit",
    trigger_source: "visit_log",
    billing_cycle: "immediate",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 10,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers unscheduled or early termination visits driven by patient status, safety, or sponsor-directed schedule changes.",
    default_rate: 425,
    range_low: 275,
    range_high: 650,
    percent_rate: null,
  },
  {
    fee_code: "INV-SAE-001",
    fee_name: "SAE Reporting & Review Fee",
    category: "invoiceable",
    unit: "per_sae",
    trigger_type: "safety",
    trigger_source: "sae_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium_high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "per_event_estimated",
    justification_template:
      "Covers SAE intake, medical review, regulatory reporting coordination, and sponsor correspondence per reported event.",
    default_rate: 275,
    range_low: 150,
    range_high: 450,
    percent_rate: null,
  },
  {
    fee_code: "INV-DRY-001",
    fee_name: "Dry Ice, Shipping & Specimen Handling",
    category: "pass_through",
    unit: "per_shipment",
    trigger_type: "shipment",
    trigger_source: "shipment_log",
    billing_cycle: "monthly_or_batch",
    payment_terms: "net_30",
    priority: "medium_high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "cost_plus_markup",
    justification_template:
      "Reimburses dry ice, courier, packaging, and chain-of-custody handling for outbound specimen shipments.",
    default_rate: 85,
    range_low: 40,
    range_high: 200,
    percent_rate: null,
  },
  {
    fee_code: "INV-PHARM-001",
    fee_name: "Pharmacy / IP Preparation & Dispensing",
    category: "invoiceable",
    unit: "per_visit_or_dose",
    trigger_type: "pharmacy",
    trigger_source: "pharmacy_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium_high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers investigational product preparation, labeling checks, dispensing, and pharmacy documentation tied to patient visits.",
    default_rate: 95,
    range_low: 50,
    range_high: 180,
    percent_rate: null,
  },
  {
    fee_code: "INV-CONC-001",
    fee_name: "Patient Concierge / Reminder Fee",
    category: "invoiceable",
    unit: "per_patient_month",
    trigger_type: "monthly_management",
    trigger_source: "patient_mgmt_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "per_event_estimated",
    justification_template:
      "Covers proactive scheduling support, visit reminders, and lightweight care navigation to protect retention and compliance.",
    default_rate: 120,
    range_low: 60,
    range_high: 220,
    percent_rate: null,
  },
  {
    fee_code: "INV-MON-001",
    fee_name: "On-site Monitoring Visit Support",
    category: "invoiceable",
    unit: "per_visit",
    trigger_type: "monitoring",
    trigger_source: "monitoring_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers coordination, space, copies, and staff time required to host and support on-site monitoring visits.",
    default_rate: 650,
    range_low: 400,
    range_high: 950,
    percent_rate: null,
  },
  {
    fee_code: "INV-QUERY-001",
    fee_name: "Query Resolution Fee",
    category: "invoiceable",
    unit: "per_batch_or_hour",
    trigger_type: "query_resolution",
    trigger_source: "edc_query_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "per_event_estimated",
    justification_template:
      "Covers investigation, source verification, and closure of data queries generated in the EDC or related systems.",
    default_rate: 175,
    range_low: 75,
    range_high: 350,
    percent_rate: null,
  },
  {
    fee_code: "INV-ARC-001",
    fee_name: "Long-term Archiving Fee",
    category: "closeout",
    unit: "one_time",
    trigger_type: "closeout",
    trigger_source: "closeout_log",
    billing_cycle: "at_closeout",
    payment_terms: "net_30",
    priority: "high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 15,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers long-term storage, indexing, and retrieval readiness for essential study records after database lock.",
    default_rate: 4500,
    range_low: 2500,
    range_high: 7500,
    percent_rate: null,
  },
  {
    fee_code: "INV-CLO-001",
    fee_name: "Study Close-out Fee",
    category: "closeout",
    unit: "one_time",
    trigger_type: "closeout",
    trigger_source: "monitoring_log",
    billing_cycle: "at_closeout",
    payment_terms: "net_30",
    priority: "medium_high",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 15,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers final close-out activities, reconciliations, and handoffs required to complete the study at site level.",
    default_rate: 2800,
    range_low: 1500,
    range_high: 4500,
    percent_rate: null,
  },
  {
    fee_code: "ADMIN-OVER-001",
    fee_name: "Administrative / Overhead Fee",
    category: "administrative",
    unit: "percent_of_total",
    trigger_type: "budget_rule",
    trigger_source: "budget_engine",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: false,
    invoice_required: false,
    max_days_to_invoice: null,
    sponsor_visible: true,
    engine_behavior: "pricing_rule",
    default_rate_strategy: "percent_of_total",
    justification_template:
      "Reflects site operational overhead required to support compliant execution, including facilities, utilities, insurance, and core administrative infrastructure.",
    default_rate: null,
    range_low: null,
    range_high: null,
    percent_rate: 10.0,
  },
  {
    fee_code: "ADMIN-IRB-001",
    fee_name: "Annual IRB Continuing Review",
    category: "administrative",
    unit: "per_year",
    trigger_type: "annual_review",
    trigger_source: "irb_log",
    billing_cycle: "annual",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 15,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers annual continuing review preparation, submission, and follow-up correspondence required to maintain IRB approval.",
    default_rate: 800,
    range_low: 500,
    range_high: 1300,
    percent_rate: null,
  },
  {
    fee_code: "ADMIN-TECH-001",
    fee_name: "Technology Setup / CTMS-eReg Access Fee",
    category: "startup",
    unit: "one_time",
    trigger_type: "setup",
    trigger_source: "tech_access_log",
    billing_cycle: "immediate",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 5,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers CTMS/eReg provisioning, account setup, training coordination, and validation of technology access for the study team.",
    default_rate: 900,
    range_low: 400,
    range_high: 1600,
    percent_rate: null,
  },
  {
    fee_code: "RECR-ADV-001",
    fee_name: "Recruitment / Advertising Support Fee",
    category: "invoiceable",
    unit: "one_time_or_campaign",
    trigger_type: "recruitment_campaign",
    trigger_source: "recruitment_log",
    billing_cycle: "immediate",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 10,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers advertising setup, vendor coordination, pre-screening support, and campaign tracking tied to recruitment goals.",
    default_rate: 2400,
    range_low: 1000,
    range_high: 5000,
    percent_rate: null,
  },
  {
    fee_code: "CONT-BUF-001",
    fee_name: "Contingency Buffer (Imprevistos)",
    category: "contingency",
    unit: "percent_of_total",
    trigger_type: "budget_rule",
    trigger_source: "budget_engine",
    billing_cycle: "at_signature",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: false,
    invoice_required: false,
    max_days_to_invoice: null,
    sponsor_visible: true,
    engine_behavior: "negotiation_only",
    default_rate_strategy: "percent_of_total",
    justification_template:
      "Provides a negotiated contingency allowance for unplanned operational tasks not explicitly itemized in the per-event schedule.",
    default_rate: null,
    range_low: null,
    range_high: null,
    percent_rate: 5.0,
  },
  {
    fee_code: "PASS-LAB-001",
    fee_name: "External Lab Processing Fee",
    category: "pass_through",
    unit: "per_test",
    trigger_type: "lab_processing",
    trigger_source: "lab_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "cost_plus_markup",
    justification_template:
      "Passes through external laboratory processing charges with agreed handling for collection, shipping, and reconciliation.",
    default_rate: 120,
    range_low: 40,
    range_high: 280,
    percent_rate: null,
  },
  {
    fee_code: "PASS-TRAV-001",
    fee_name: "Patient Travel / Stipend Reimbursement",
    category: "pass_through",
    unit: "per_visit",
    trigger_type: "patient_visit_completed",
    trigger_source: "visit_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "cost_plus_markup",
    justification_template:
      "Reimburses patient travel, parking, and stipend amounts executed per sponsor-approved policy and visit attendance.",
    default_rate: 150,
    range_low: 50,
    range_high: 400,
    percent_rate: null,
  },
  {
    fee_code: "INV-IMAG-001",
    fee_name: "Central Imaging / ECG Reading Submission",
    category: "invoiceable",
    unit: "per_submission",
    trigger_type: "central_submission",
    trigger_source: "imaging_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers upload, QC, transmission, and vendor fees for central imaging or ECG reads per protocol requirements.",
    default_rate: 210,
    range_low: 90,
    range_high: 450,
    percent_rate: null,
  },
  {
    fee_code: "INV-DEV-001",
    fee_name: "Device / Wearable Management Fee",
    category: "invoiceable",
    unit: "per_patient",
    trigger_type: "device_issued",
    trigger_source: "device_log",
    billing_cycle: "monthly",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: true,
    invoice_required: true,
    max_days_to_invoice: 30,
    sponsor_visible: true,
    engine_behavior: "operational_billable",
    default_rate_strategy: "range_based",
    justification_template:
      "Covers device provisioning, training, sync support, and accountability tracking for patient-worn equipment during the study.",
    default_rate: 280,
    range_low: 120,
    range_high: 520,
    percent_rate: null,
  },
  {
    fee_code: "INF-ADJ-001",
    fee_name: "Inflation Adjustment Clause",
    category: "contingency",
    unit: "percent_per_year",
    trigger_type: "annual_adjustment",
    trigger_source: "budget_engine",
    billing_cycle: "annual",
    payment_terms: "net_30",
    priority: "medium",
    auto_create_billable: false,
    invoice_required: false,
    max_days_to_invoice: null,
    sponsor_visible: true,
    engine_behavior: "negotiation_only",
    default_rate_strategy: "annual_uplift",
    justification_template:
      "Documents an agreed annual uplift mechanism for applicable pass-through and service rates in line with contracted inflation terms.",
    default_rate: null,
    range_low: null,
    range_high: null,
    percent_rate: 2.5,
  },
] as const

export const STARTER_FEES_EXTENDED_CODES = STARTER_FEES_EXTENDED.map((f) => f.fee_code)

export const ALL_STARTER_TEMPLATE_FEE_CODES = [
  ...CORE_V1_CLINICAL_FEE_CODES,
  ...STARTER_FEES_EXTENDED_CODES,
] as const

export function feeCodesUnique(codes: readonly string[]): boolean {
  return new Set(codes).size === codes.length
}
