import type { ClaimsLedgerRow } from "@/lib/cliniq-core/claims/types"

export const claimsDemoStudyId = "POST-AWARD-DEMO-1"
export const claimsDemoSponsorId = "SPN-ACME-2042"

/** Reference date for aging in the demo UI */
export const claimsMockAsOf = "2026-04-15T12:00:00.000Z"

const periodMarch = { invoicePeriodStart: "2026-03-01", invoicePeriodEnd: "2026-03-31" }

/**
 * Operational ledger rows after execution: visits, fees, and exception scenarios.
 */
export const claimsOperationalLedgerRows: ClaimsLedgerRow[] = [
  {
    studyId: claimsDemoStudyId,
    sponsorId: claimsDemoSponsorId,
    subjectId: "SUB-101",
    visitName: "Visit 2",
    eventDate: "2026-03-05T10:00:00.000Z",
    lineCode: "V2",
    label: "On-site visit 2",
    amount: 640,
    approved: true,
    supportDocumentationComplete: true,
    supportNote: "Source document on file",
    billableInstanceId: "bill-v2-101",
    eventLogId: "evt-v2-101",
    ...periodMarch,
  },
  {
    studyId: claimsDemoStudyId,
    sponsorId: claimsDemoSponsorId,
    subjectId: "SUB-102",
    visitName: "Visit 2",
    eventDate: "2026-03-18T14:30:00.000Z",
    lineCode: "V2",
    label: "On-site visit 2",
    amount: 640,
    approved: true,
    supportDocumentationComplete: true,
    billableInstanceId: "bill-v2-102",
    eventLogId: "evt-v2-102",
    ...periodMarch,
  },
  {
    studyId: claimsDemoStudyId,
    sponsorId: claimsDemoSponsorId,
    subjectId: "SUB-103",
    visitName: "Screening",
    eventDate: "2026-03-12T09:00:00.000Z",
    lineCode: "SF",
    label: "Screen failure fee",
    amount: 350,
    approved: true,
    supportDocumentationComplete: true,
    billableInstanceId: "bill-sf-103",
    eventLogId: "evt-sf-103",
    ...periodMarch,
  },
  {
    studyId: claimsDemoStudyId,
    sponsorId: claimsDemoSponsorId,
    subjectId: "—",
    visitName: "N/A",
    eventDate: "2026-03-20T16:00:00.000Z",
    lineCode: "AMEND",
    label: "Amendment review fee",
    amount: 1200,
    approved: true,
    supportDocumentationComplete: true,
    billableInstanceId: "bill-amend-01",
    eventLogId: "evt-amend-01",
    ...periodMarch,
  },
  {
    studyId: claimsDemoStudyId,
    sponsorId: claimsDemoSponsorId,
    subjectId: "SUB-104",
    visitName: "Visit 1",
    eventDate: "2026-03-22T11:00:00.000Z",
    lineCode: "LAB",
    label: "Local lab draw",
    amount: 95,
    approved: true,
    supportDocumentationComplete: false,
    supportNote: "Awaiting lab requisition scan",
    billableInstanceId: "bill-lab-104",
    eventLogId: "evt-lab-104",
    ...periodMarch,
  },
  {
    studyId: claimsDemoStudyId,
    sponsorId: claimsDemoSponsorId,
    subjectId: "SUB-105",
    visitName: "Visit 3",
    eventDate: "2026-03-25T13:00:00.000Z",
    lineCode: "V3",
    label: "On-site visit 3",
    amount: 720,
    approved: true,
    supportDocumentationComplete: true,
    disputed: true,
    disputeReason: "Sponsor disputes visit window eligibility",
    billableInstanceId: "bill-v3-105",
    eventLogId: "evt-v3-105",
    ...periodMarch,
  },
  {
    studyId: claimsDemoStudyId,
    sponsorId: claimsDemoSponsorId,
    subjectId: "SUB-106",
    visitName: "Visit 1",
    eventDate: "2025-11-04T09:00:00.000Z",
    lineCode: "V1",
    label: "On-site visit 1",
    amount: 580,
    approved: true,
    supportDocumentationComplete: true,
    markedOverdue: true,
    supportNote: "Prior period — not yet invoiced",
    billableInstanceId: "bill-v1-overdue",
    eventLogId: "evt-v1-overdue",
    invoicePeriodStart: "2025-11-01",
    invoicePeriodEnd: "2025-11-30",
  },
]
