/**
 * CLI: run Module 3 budget gap analysis from JSON inputs; write canonical JSON + CSV.
 * CSV is generated by re-reading the JSON file.
 *
 *   npx tsx scripts/run-budget-gap-analysis.ts --internal=./internal.json --sponsor=./sponsor.json
 *   npx tsx scripts/run-budget-gap-analysis.ts --internal=... --sponsor=... --studyMeta=./meta.json
 *   npx tsx scripts/run-budget-gap-analysis.ts --internal=... --sponsor=... --siteNegotiationVariables=./policy.json --outDir=./out
 */

import { mkdirSync, readFileSync } from "node:fs"
import { join } from "node:path"

import { compareSponsorBudgetToInternalBudget } from "../lib/cliniq-core/budget-gap/compare"
import { writeBudgetGapAnalysisCsvFromJsonFile } from "../lib/cliniq-core/budget-gap/export-budget-gap-csv-node"
import { writeBudgetGapAnalysisJson } from "../lib/cliniq-core/budget-gap/export-budget-gap-json-node"
import type {
  CompareBudgetInput,
  InternalBudgetLine,
  SiteNegotiationVariables,
  SponsorBudgetLine,
} from "../lib/cliniq-core/budget-gap/types"

const JSON_NAME = "budget_gap_analysis.json"
const CSV_NAME = "budget_gap_analysis.csv"

function parseArgs(argv: string[]): Record<string, string> {
  const out: Record<string, string> = {}
  for (const raw of argv) {
    if (!raw.startsWith("--")) continue
    const body = raw.slice(2)
    const eq = body.indexOf("=")
    if (eq === -1) {
      out[body] = "true"
      continue
    }
    out[body.slice(0, eq)] = body.slice(eq + 1)
  }
  return out
}

function requireArg(args: Record<string, string>, key: string): string {
  const v = args[key]
  if (v === undefined || v === "") {
    console.error(`Missing required argument: --${key}=PATH`)
    process.exit(1)
  }
  return v
}

function readJsonFile(path: string, label: string): unknown {
  let text: string
  try {
    text = readFileSync(path, "utf8")
  } catch (e) {
    console.error(`Failed to read ${label} file ${path}:`, e instanceof Error ? e.message : e)
    process.exit(1)
  }
  try {
    return JSON.parse(text) as unknown
  } catch (e) {
    console.error(`Invalid JSON in ${label} (${path}):`, e instanceof Error ? e.message : e)
    process.exit(1)
  }
}

function asLineArray(data: unknown, label: string): InternalBudgetLine[] | SponsorBudgetLine[] {
  if (!Array.isArray(data)) {
    console.error(`${label}: expected a JSON array of line objects.`)
    process.exit(1)
  }
  return data as InternalBudgetLine[] | SponsorBudgetLine[]
}

function main() {
  const args = parseArgs(process.argv.slice(2))
  const internalPath = requireArg(args, "internal")
  const sponsorPath = requireArg(args, "sponsor")
  const outDir = args.outDir ?? process.cwd()

  const internalRaw = readJsonFile(internalPath, "internal lines")
  const sponsorRaw = readJsonFile(sponsorPath, "sponsor lines")
  const internalLines = asLineArray(internalRaw, "Internal lines") as InternalBudgetLine[]
  const sponsorLines = asLineArray(sponsorRaw, "Sponsor lines") as SponsorBudgetLine[]

  let studyMeta: CompareBudgetInput["studyMeta"] = {}
  if (args.studyMeta !== undefined && args.studyMeta !== "") {
    const meta = readJsonFile(args.studyMeta, "studyMeta")
    if (meta === null || typeof meta !== "object" || Array.isArray(meta)) {
      console.error("studyMeta: expected a JSON object.")
      process.exit(1)
    }
    studyMeta = meta as CompareBudgetInput["studyMeta"]
  }

  let siteNegotiationVariables: SiteNegotiationVariables | undefined
  const policyPath = args.siteNegotiationVariables ?? args.policy
  if (policyPath !== undefined && policyPath !== "") {
    const pol = readJsonFile(policyPath, "siteNegotiationVariables")
    if (pol === null || typeof pol !== "object" || Array.isArray(pol)) {
      console.error("siteNegotiationVariables: expected a JSON object.")
      process.exit(1)
    }
    siteNegotiationVariables = pol as SiteNegotiationVariables
  }

  const input: CompareBudgetInput = {
    internalLines,
    sponsorLines,
    studyMeta,
    ...(siteNegotiationVariables !== undefined
      ? { siteNegotiationVariables }
      : {}),
  }

  const result = compareSponsorBudgetToInternalBudget(input)

  const jsonPath = join(outDir, JSON_NAME)
  const csvPath = join(outDir, CSV_NAME)
  mkdirSync(outDir, { recursive: true })
  writeBudgetGapAnalysisJson(jsonPath, result)
  writeBudgetGapAnalysisCsvFromJsonFile(csvPath, jsonPath)

  const totalRows = result.gapLines.length + result.missingInvoiceables.length
  const statusCounts = new Map<string, number>()
  for (const l of result.gapLines) {
    statusCounts.set(l.status, (statusCounts.get(l.status) ?? 0) + 1)
  }
  for (const m of result.missingInvoiceables) {
    statusCounts.set(m.status, (statusCounts.get(m.status) ?? 0) + 1)
  }
  const statusSummary = [...statusCounts.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([s, n]) => `${s}=${n}`)
    .join(", ")

  console.log(`total_lines=${totalRows}`)
  console.log(`status_counts: ${statusSummary || "(none)"}`)
  console.log("summary_alerts:")
  for (const a of result.summary.primaryAlerts) {
    console.log(`  - ${a}`)
  }
  console.log(`json: ${jsonPath}`)
  console.log(`csv: ${csvPath}`)
}

main()
